### ISSUE TITLE
Spec is unclear about context propagation when different executor supplied to Async methods

### ISSUE THREAD

**Issue by njr-11** [eclipse/microprofile-concurrency#110]
In addition to the usual patterns,

`stage2 = stage1.thenRun(action2);`

`stage3 = stage2.thenRunAsync(action3);`

the CompletionStage/CompletableFuture API also allow you to override the executor that is used to run the action for a particular stage via methods like,

`stage4 = stage3.thenRunAsync(action4, executor);`

In the former two cases, it is clear that the managed executor's own configuration of propagated/cleared context types determine how thread context is captured and later applied when running the action.

However, in the latter case, the user is explicitly asking for a different executor - one that can be a managed executor as well and might have an entirely different configuration for propagated/cleared context types.  The spec doesn't currently clarify which executor's configuration is used in this case.

We should clarify this so that implementations will be consistent and users will know what behavior to rely upon.

**Comment by njr-11** [comment]
My own thoughts on this are that we ought to clarify it to use the configuration of the executor that the customer supplies specifically for that stage.  Given the requirement to use the supplied executor to run the action, it seems natural that the supplied executor also determines the context propagation for the action.  I'll add a pull to this issue with a proposal on how we can update the JavaDoc for this.

**Comment by FroMage** [comment]
My opinion is that the two first versions use the `ThreadContext` settings tied to the `CompletionStage` itself for propagation, while the last version (with specified executor) has a choice between using its own settings or the settings of the executor, but only if it is managed.

In the wild, most users will deal with interop with async libs such as RxJava1&2 or Reactor and those have their own executors that we can't turn into managed ones. Additionally, executors are expensive and when using libs that have executors (Vert.x, Netty, others) we are going to have to work with them, and that includes sending our `CompletionStage`s to those executors, so it would be very useful to have context propagated to non-managed executors.

If this is indeed a desirable behaviour, it becomes hard to justify using the executor's `ThreadContext` settings if it is managed, and otherwise use the settings from the current `CompletionStage`, so I would stick to always using the `CompletionStage` settings for all three API forms, regardless of the passed executor.

**Comment by andymc12** [comment]
I think @njr-11's initial suggestion (of not propagating the contexts) is more intuitive from a coding perspective, and I think that aligns with the general ideas discussed in the JAX-RS mail list around the reactive client APIs.

That said, I agree with @FroMage's point that some executors will be unmanaged, but to be useful in the app must have some contexts propagated.  If using `ThreadContext` can allow users to explicitly propagate contexts, that might be the better solution overall.  That ensures that users get the context configuration of the passed-in executor, but gives them the freedom to propagate contexts to an unmanaged executor if necessary.

Just my two cents.  Thanks!

**Comment by FroMage** [comment]
Could you point me to the discussions on the JAX-RS mailing list?

**Comment by andymc12** [comment]
@FroMage This is the discussion I was referring to:
https://javaee.groups.io/g/jaxrs-spec/topic/clarification_regarding/7560658?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,7560658

Thanks

**Comment by njr-11** [comment]
Pull #111 needed an update according to the discussion we had (the part everyone agreed on) to formally state that an already-contextualized action takes precedence if supplied to a completion stage, and in the course of making that update, I realized that the combination of this clarification along with the special requirement around a supplied managed executor does make the doc fairly complex, so I also looked into how we would go about documenting the opposing case, where the same managed executor's config always determines context propagation, and it did seem a bit simpler.  I'm leaving pull #111 in that state for now given that it was the most popular option on the call.  It can be switched again if necessary, but it does seem that either of us with the minority view felt strongly enough on this, so I expect we will end up with the approach that is now documented under the pull unless there is further feedback to the contrary.
