### ISSUE TITLE
Questions about ThreadContextProvider and propagate/unchanged

### ISSUE THREAD

**Issue by FroMage** [eclipse/microprofile-concurrency#12]
- I think there's a discrepancy between the naming of `ThreadContextBuilder.propagate` and `ThreadContextBuilder.unchanged`. I think the first should either be `propagated` or the second be `ignore`.
- `ThreadContextBuilder` has `propagate`/`unchanged` but `ManagedExecutionBuilder` only has `context`, which I guess is the equivalent of `propagate`. The name should be coherent, and the functionality to set `unchanged` contexts too.
- The relation between `propagate` and `unchanged` sets, and the implied `cleared` set should be clarified:
-- For `propagate` we take all specified providers plus all the prerequisites, recursively. For `unchanged` the docs say to take all specified providers plus all those that have it as prerequisite, recursively. I wonder why the relation is reversed here? 
-- Once we have both sets, I assume the `cleared` set is the rest of the providers, but I suspect that we have to also make sure that none of the recursive prerequisites of the `cleared` set are within either of the `propagate` or `unchanged` set, right?

**Comment by njr-11** [comment]
I agree there is a discrepancy in the tense used for naming.  The builders are still under review at this point, so I'll aim to make that part of the change within the original pull.  ThreadContextConfig is already using `unchanged`, so I'll plan to leave ThreadContextBuilder `unchanged` and switch ThreadContextBuilder `propagate` and ManagedExecutorBuilder `context` to `propagated` for consistency.

ManagedExecutorBuilder (and corresponding ManagedExecutorConfig annotation) very intentionally leave out the `unchanged` set of contexts.  This is because `unchanged` results in non-deterministic behavior when applied to an executor/completion stage/completable future which are able to run the task/action on a variety of threads outside the control of the user.  One of the core driving reasons behind this spec was to provide a dependable/deterministic/predictable/safe behavior for completion stages and completable futures.  Including `unchanged` on the managed executors would undermine that.  This is why it is omitted.
In the case of ThreadContext, on the other hand, the user has more control over the contextualized task.  Specifically, they might opt to run it inline on a particular thread, so there is actually a valid case for wanting to preserve certain existing context on the thread unchanged.

Thanks for pointing out the issue with the prerequisites, I'll look into that as well.

**Comment by njr-11** [comment]
Please review the fixes to the above under pull #14, and add a comment indicating if you believe it is ready to be merged by a committer.  Thanks again for catching these issues!
