### ISSUE TITLE
@ThreadContextConfig / @ManagedExecutorConfig are superfluous

### ISSUE THREAD

**Issue by gavinking** [eclipse/microprofile-concurrency#135]
Currently we have two different ways for a user to configure a `ThreadContext` or a `ManagedExecutor`:

- in procedural code using a `Builder`, or
- using a `Config` annotation that performs injection.

The annotation-based approach is ever so slightly less verbose, and the builder-based approach lets one specify attributes based on runtime conditions, but other than that there's not much difference AFAICT.

It's not necessary to have two ways to do this thing. Assuming that the extra flexibility of a `Builder` is actually truly useful, then I would get rid of the annotation. It is *very* easy in CDI to create a little producer method that builds something and binds it to the CDI application scope. It is *not* the CDI way to have injection annotations with lots of configuration attributes that then get copy/pasted all over the codebase.

**Comment by njr-11** [comment]
The builders were originally added so that MicroProfile Concurrency could still be used in the absence of a CDI implementation (one of the original contributors asked for this).  For the most part, the capability of the builders does overlap the capability of the config annotations.  The builders add some additional versatility due to their programmatic nature and I think they make user errors more debuggable due to exception stacks pointing directly back to the line of application code where it was misconfigured.  On the other hand, the container-injected CDI instances do provide a more concise way of specifying configuration, and they also ended up allowing for a convenient way to let the user [override individual instances via MP Config](https://github.com/eclipse/microprofile-concurrency/blob/master/spec/src/main/asciidoc/mpconfig.asciidoc) even if the application isn't written with MP Config awareness in mind.

> injection annotations with lots of configuration attributes that then get copy/pasted all over the codebase.

The intent was to avoid this sort of thing, in that the spec also included a `NamedInstance` qualifier specifically to allow for a single injection point with a config annotation to act as an implicit producer, such that injection points elsewhere could inject that same instance by specifying only the `NamedInstance` qualifier with the same value.

My comments above are intended, as much as possible, to be an unbiased summary of the differences that I am aware of between the builders and the config annotations.

@manovotn who works on WELD and has been heavily involved in this spec has a lot of depth and expertise in this area and will be better able to comment on this issue and assess what action should be taken here.

**Comment by aguibert** [comment]
Personally I agree with @gavinking here. I think the config annotations don't add much value beyond what the builders offer. Additionally, the config annotations add a lot of complexity to the spec because of instance sharing considerations.

If a user wants to inject things with CDI, a standard field-based producer is simple enough:
```java
@Produces @ApplicationScoped
ManagedExecutor exec = ManagedExecutor.builder()
          .maxAsync(5)
          .propagated(...)
          .cleared(...)
          .build();
```

Since we've already spent a disproportionately large amount of time discussing the config annotations, I'm fine leaving things as they currently are in the spec as a compromise. However, personally I am still in favor of scrapping the config annotations entirely.

**Comment by FroMage** [comment]
That's a tough question. I guess I'm neither for nor against them, except I assume we have use-cases for looking up commonly configured `ThreadContext` (or `ManagedExecutor`) objects, such as "all contexts propagated", "all contexts cleared", "all contexts propagated except transaction". We could argue that getting those injected with a name (or qualifier annotation) is easier than calling the builder, but really we could have static methods for those that would be simpler than either form of injection.

I would say we keep them because we spent a lot of time implementing them, and it's possible that users will prefer them over the builders, but those are pretty weak arguments (from a non-implementer perspective). Consistency with other MP specs could be a valid reason to keep them, if other MP specs have equivalent annotation/builder splits.

**Comment by manovotn** [comment]
I think this complaint comes a bit late as, much like others above me said, we've already spent some considerable time designing that. It is true that you can instead use builders and producers.
However, this puts some extra weight on user to correctly define the producer - for instance using other then application scope can result in unexpected behaviour. The way we have it, you get everything out of the box, no handling the create/destroy, all beans for your IPs are automagically added, sharing included. You can still have your own producers if you wish to but the way I see it, when you write a CDI producer, you are trying to turn an object that wasn't meant to be a bean into one.

Like you said, there isn't a clear benefit you get from this approach as opposed to going pure builder model. It's more like giving users multiple options, you can use whichever approach you prefer. Having it though makes CDI a first class citizen. 

Furthermore I would say that purely annotation-based approach is rather popular lately so having these annotations in place supports this model. I am not saying the model is better or clearer, I have just seen it used quite often, including some configuration on it.

So overall, unless having these annotations somehow blocks us, I don't really see any strong argument to remove them (albeit the arguments to keep them are equally weak).

**Comment by gavinking** [comment]
@njr-11

> the container-injected CDI instances do provide a more concise way of specifying configuration

Well, on the contrary, they are only just *barely* more concise and only when you get down to the level of counting tokens. They're no simpler in terms of writability/readability, and it's at least arguable that they *add* complexity by forcing the user to have to decide between two essentially equivalent constructs that do the same thing.

>  On the other hand, the container-injected CDI instances do provide a more concise way of specifying configuration

No. This is pretty much a misuse of CDI. The whole point of CDI is that you want to avoid doing configuration at injection points. You want to do it in one central place (a producer), and in that case it makes no difference whether it's a builder or an annotation.

> The intent was to avoid this sort of thing, in that the spec also included a `NamedInstance` qualifier 

Ugh. If you mean `@Named`, that's also a misuse of CDI. One shouldn't inject on the basis of stringly-typed identifiers. Those are only really for use within dynamically-typed UI definitions.

**Comment by gavinking** [comment]
> I would say we keep them because we spent a lot of time implementing them

> I think this complaint comes a bit late as, much like others above me said, we've already spent some considerable time designing that. 

Sorry, folks, but these are *really* bad arguments for making an API more complex. I've had to remove things I liked from a spec based on feedback in the weeks before release (yeah, the CDI spec, ironically), and I did it happily because it was the right thing to do and made the spec simpler and easier to learn.

Time you've spent designing/implementing something not very useful is a [sunk cost](https://en.wikipedia.org/wiki/Sunk_cost) and doesn't come into this decision.

**Comment by gavinking** [comment]
>  It is true that you can instead use builders and producers. However, this puts some extra weight on user to correctly define the producer

But they should to use a producer whether they're using builders or annotations. So this argument seems to fail.

> for instance using other then application scope can result in unexpected behaviour.

AFAICT, the "unexpected behavior" is non-harmful.

> The way we have it, you get everything out of the box, no handling the create/destroy, all beans for your IPs are automagically added, sharing included. 

Except that you don't. What you're doing is leading the user down the wrong path of re-defining in the configuration at the injection point, instead of having the configuration in one place.

> You can still have your own producers if you wish to but the way I see it, when you write a CDI producer, you are trying to turn an object that wasn't meant to be a bean into one.

This statement makes no sense to me at all, and I wrote the CDI spec.

>  I don't really see any strong argument to remove them 

It makes (a) the API surface smaller, and (b) the spec simpler. These are always strong arguments.

**Comment by njr-11** [comment]
I didn't state a position on this in the previous posts, which were mostly focused on trying to ensure that the two approaches were fully understood, so that we can come to the right agreement for the right reasons.  I am willing to remove `@ManagedExecutorConfig` and `@ThreadContextConfig` from the spec if we have agreement from @manovotn and other contributors who had previously advocated for them.

There is one further area that still needs to be clarified, which is `@NamedInstance`, which is not the same as `@Named`

> Ugh. If you mean `@Named`, that's also a misuse of CDI. One shouldn't inject on the basis of stringly-typed identifiers. Those are only really for use within dynamically-typed UI definitions.

As one of those who were previously advocating for application-defined producers vs the config annotations, the main obstacle we saw in that case was the learning curve for the basic user to create their own CDI qualifier(s) in order to differentiate the various managed executors that they produced.  I suggested it would be convenient to use the built-in `@Named` annotation for this, but was told that isn't proper usage and was directed that the right approach would be for us to define our own qualifier of the same form for this purpose, which we called `@NamedInstance`.  Based on the reasoning behind your arguments against `@Named`, I expect you would have the same concerns with `@NamedInstance` as well.  If so, do you have a better alternative here?

**Comment by gavinking** [comment]
> There is one further area that still needs to be clarified, which is `@NamedInstance`, which is not the same as `@Named`

Where is `@NamedInstance` defined?

> Based on the reasoning behind your arguments against `@Named`, I expect you would have the same concerns with `@NamedInstance` as well. If so, do you have a better alternative here?

Well if it amounts to injecting an object on the basis of a string name, then it's isomorphic to `@Named`, and I don't see why you would not just use the built-in one.

But yeah, it's the wrong way to use CDI. String-based names are untypesafe and very fragile. The whole point of the system of injection in CDI is that you're supposed to use typesafe identifiers for things.

> the main obstacle we saw in that case was the learning curve for the basic user to create their own CDI qualifier(s) in order to differentiate the various managed executors that they produced

Well in the simple and I imagine quite common case that they have exactly one `ManagedExecutor`, there's no need for a qualifier annotation. (It's implicitly the `@Default ManagedExecutor`.

Once things get more complex, and you need to add a second `ManagedExecutor` to your app (which I imagine is not a getting-started type usecase), then, yes, you would typically define a custom qualifier annotation for that. But this is something that's totally plain-vanilla CDI usage, and all users are expected to understand how to do that. 

(Note: you do *not* need to change the injection points with for the `@Default` instance when you add a non-`@Default` instance! CDI was carefully designed to avoid that need.)

**Comment by gavinking** [comment]
Ufff.

<https://github.com/eclipse/microprofile-concurrency/blob/master/api/src/main/java/org/eclipse/microprofile/concurrent/NamedInstance.java>

AFAICT, this is essentially a copy-paste job of:

<https://docs.oracle.com/javaee/6/api/javax/inject/Named.html>

Please remove it.

**Comment by gavinking** [comment]
>> I don't really see any strong argument to remove them

> It makes (a) the API surface smaller, and (b) the spec simpler. These are always strong arguments.

And, of course, (c) you're imposing a requirement that all future implementors of MP Concurrency also implement this annotation-based injection stuff.

**Comment by manovotn** [comment]
I wasn't really advocating for this, it pretty much existed by the point I started taking part in the spec.

From there I figured that there was an intention to have this CDI-first approach and we were going over it, especially over how to share it and how to implement this. In order to "support CDI" in the spec it seemed reasonable to provide this kind of structure we have here.

_So if we want to back out of that, we can, I am not blocking that_. 
Just note two things:

1. There is no feedback on usability as we ponder over this, so we cannot know what users really mean to use.
2. A conversation similar to this happened before and people seemed to be in favor of supporting CDI injection with configuration annotations so I was just kind of surprised at the change now that we have it TCK-covered and are nearing releasable state.

As a side note - the `@NamedInstance` is pretty much the same as `@Named` except that `@Named` is linked to bean names and the ability to resolve beans from just a string (in JSF for instance). We didn't want to mix the two but wanted to give user a way to name their executor that they are going to share from several points in the code while referring to them via the name they chose. That's just the background of how this came to be...

**Comment by njr-11** [comment]
On the MP Concurrency call, we confirmed that all were in agreement with the approach of removing the config annotations and NamedInstance.  This will be replaced in the spec doc with an example of the best practice of using an ApplicationScoped producer that uses the builder.

**Comment by gavinking** [comment]
Great! +1
