### ISSUE TITLE
Clarify thread context dependency errors

### ISSUE THREAD

**Issue by FroMage** [eclipse/microprofile-concurrency#18]
We should clarify what happens in the following situations:

- more than one `ThreadContextProvider` has the same `threadContextType`
- a `ThreadContextProvider` lists a `prerequisite` which is missing (no `ThreadContextProvider` has that `threadContextType`)
- a `ThreadContextProvider` depends on itself via its `prerequisite` (directly or not)
- a user requests a thread context which is in both `propagated` and `unchanged` sets, directly or via `prerequisite`

The docs currently say "must fail to inject" in two of those cases, but that's too vague: 

- Should an error be generated?
- If yes: which kind?
- If yes: at what point?
- On `ThreadContext` build time, or at context _capture_ time or at context _set_ time?

I would suggest that we do generate an error (`IllegalStateException` or a custom one), as early as possible, such as on `ThreadContext` build time, so that no `ThreadContext` instance can be obtained that would have an erroneous set of contexts to propagate/clear/ignore.

**Comment by njr-11** [comment]
Thanks for opening this. The spec could definitely use some good attention to detail on the error paths. I agree with the general guideline of reporting errors nearest to the source of the bad configuration as we can in order to offer the most clarity to the user.  A good example of this is MaangedExecutorBuilder raises IllegalArgumentException immediately upon `maxAsync` receiving an invalid value such as -100 rather than deferring until `build` or even later until the built executor is first used to submit a task.  By raising the IllegalArgumentException immediately from `maxAsync`, the exception stack will contain the `maxAsync` method call and it will be obvious to the user that they have supplied it with an invalid value.  I realize this won't always be possible, such as with an overlapping value in the `propagated` and `unchanged` sets, because the user must be given the opportunity to set both values appropriately before the `build` method validates the combination of both.

In a previous review comment, Emily asked that "fail to inject" be clarified as raising the CDI DefinitionException, in the case of the CDI annotations.  It looks like I updated the specific places that she spotted, but there are a few others that weren't noticed.  I would propose we use that precedent for invalid config throughout those annotations.  Also, it looks like I inadvertently copied some of the "fail to inject" wording into the builders, and yes, that needs to be replaced with proper exceptions.

Now that the pull request for the builders has been merged, this is a good time to go through the interfaces to clarify the error paths. I'll look into putting together a commit per the above.
