### ISSUE TITLE
Suggestion: Collect builders and config annotations into main interfaces

### ISSUE THREAD

**Issue by aguibert** [eclipse/microprofile-concurrency#41]
Currently MP Concurrency has the pattern of 3 classes per object:
- core interface (e.g. `ManagedExecutor`)
- config annotation (e.g. `@ManagedExecutorConfig`)
- builder interface (e.g. `ManagedExecutorBuilder`)

To make it a bit more obvious that these objects go together, I propose that we collect the config annotation and builder interface into the core interface as inner-classes, like this:

```java
// Single import statement for core, config, and builder
import org.eclipse.microprofile.concurrent.ManagedExecutor;

public class MyBean {
    @Inject
    @ManagedExecutor.Config(maxAsync = 5)
    public ManagedExecutor ex;
    
    @Produces
    public ManagedExecutor defaultExec() {
    		return ManagedExecutor.Builder.instance()
    			.maxAsync(5)
    			.build();
    }
}
```

**Comment by njr-11** [comment]
Thanks for the suggestion.  In general this is a good idea, but the CDI qualifier annotation `@ManagedExecutorConfig` will soon end up with a dependency on CDI  (which isn't there currently, but it is being fixed in another pull) and this proposal would result in the MP Concurrency spec having a main path dependency on CDI, which we are trying to avoid.

**Comment by njr-11** [comment]
My comment above no longer applies.  We will not be using Qualifier.  However `@ManagedExecutor.Config` looks awkward.   Moving the builder under ManageedExecutor does seem reasonable.

**Comment by manovotn** [comment]
I think moving the build class as an inner class is good idea as it makes it easier to use, +1 for that.
But I would keep the annotation as a separate class.
