### ISSUE TITLE
Convert the content of our README.adoc into the start of an official spec document

### ISSUE THREAD

**Issue by njr-11** [eclipse/microprofile-concurrency#43]
We have been using our README.adoc file as a placeholder for the Concurrency spec doc.
Need to get this converted to official spec doc in a /spec/ folder as the other MicroProfile specs are doing.

**Comment by manovotn** [comment]
Do I understand it correctly that in Opt 53 you blow up if user does the following? Since it violates the rule for default config as qualifier is actually present (`...injection point where qualifiers and config annotation are absent.`).

```
@Inject
@NamedInstance("foo")
ManagedExecutor e;
```


As for Opt 54, I would formulate the last point something like this:

* The container creates, per unique name, a new `ManagedExecutor` instance equivalent to `ManagedExecutorConfig()` when no `ManagedExecutor` injection point with given unique name defines custom configuration using `@ManagedExecutorConfig`.

In order to avoid excessive notions of other qualifiers present on IPs, you could add something like this to spec:

Container provides injectable instances of type `ManagedExecutor` and `ThreadContext` for all injection points annotated with either `@NamedInstance` qualifier or `@ManagedExecutorConfig`/`@ThreadContextConfig` annotations respectively, or none of these.

(_Although from CDI PoV it is obvious that you won't provide a bean for a qualifier you don't even know beforehand. So I would just discard that altogether and not mention other qualifiers and focus on what spec itself provides._)

**Comment by njr-11** [comment]
Yes, under Option 53, the example you describe is an error case (assuming the `foo` instance isn't produced elsewhere),

> Do I understand it correctly that in Opt 53 you blow up if user does the following? Since it violates the rule for default config as qualifier is actually present (`...injection point where qualifiers and config annotation are absent.`).
> 
> ```
> @Inject
> @NamedInstance("foo")
> ManagedExecutor e;
> ```

I've been thinking about how I wrote up Option 54, and I starting to think that my previous representation of it is unfair because I started by trying to make the first and second bullet points match up between both options for a simpler comparison.  However, those two bullet points are biased toward Option 53 because I wrote it up first and then tried to make Option 54 fit.  And this sent us down a path for 54 that causes it to look more complex than it should.

If I abandon that approach, here is another way of stating Option 54 (also omitting discussion about the possibility of other qualifiers), that at least to me, seems much more straightforward conceptually,

Option 54 (revised):

- `@NamedInstance` is a standard CDI Qualifier that identifies the unique name of a `ManagedExecutor`. Absent `@NamedInstance`, the unique name is the fully qualified class and field name of the injection point, with `.` as delimiter.
- The container creates, per unique name, a new `ManagedExecutor` instance, if the application does not produce one.
- When `@ManagedExecutorConfig` annotates an injection point, it customizes the configuration of the `ManagedExecutor` instance that has the respective unique name. Otherwise, the defaults from `@ManagedExecutorConfig()` apply for that instance.

The second sentence of bullet point 1 should really be added to both 53 and 54.

Option 53 (revised):

- `@NamedInstance` is a standard CDI Qualifier that identifies the unique name of a ManagedExecutor. Absent `@NamedInstance`, the unique name is the fully qualified class and field name of the injection point, with `.` as delimiter.
- `@ManagedExecutorConfig` annotates an injection point for `ManagedExecutor` such that the container creates a new instance with the specified configuration.
- The container creates a new `ManagedExecutor` instance equivalent to `@ManagedExecutorConfig()` per injection point where qualifiers and config annotation are absent.

Given this, I am now in agreement that Option 54 can be presented in a clear and concise manner that will be intuitive for users.  I would also like @aguibert to comment on this, who had raised a similar issue in case I am missing anything.

**Comment by manovotn** [comment]
`The container creates, per unique name, a new ManagedExecutor instance, if the application does not produce one.`

Not sure we need the bit about not producing one if user does.
We simply provide beans (metadata) for all unique names. If user provides their own producer as an enabled alternative, their bean definition (defined as a producer) will be used instead. That's just how CDI works. I think we could just leave it out.

**Comment by njr-11** [comment]
It's fine to omit that if it's obvious to users who know CDI well enough to be defining their own producers.  Although we don't want to force them to use Alternative here.  If they define a producer for the unique name at all, theirs ought to be used.

**Comment by manovotn** [comment]
Using an alternative is the de-facto standard via CDI when you know your container provides the "basic" bean. If you want to replace that, a well known way is to define your own bean which matches the type and qualifiers and use `@Alternative` to override that.

Other approach users often take is replace it via extension (which they can still do here).
Also note that users can still define their own producers with their custom qualifiers and that won't be affected.

What you suggest is probably doable with yet more CDI extension magic, but doesn't sounds like standard approach to me. I'd say we drop that for 1.0 as you can add that later on without breaking anything as opposed to going your way and withdrawing that behaviour later (that wouldn't be backward compatible). We'll see what people actually do and if indeed this proves useful, then we can add it.

**Comment by aguibert** [comment]
My mental model of ManagedExecutor injection can be described as follows... not sure if it fits exactly with Option 53 or not...
- The container provides a single instance of `ManagedExecutor` for `@Default ManagedExecutor` injection points, with configuration equivalent to `ManagedExecutor.Builder.build()`
- The container produces an aptly configured `ManagedExecutor` instance for each `@Default ManagedExecutor` injection point that is annotated with `@ManagedExecutorConfig`.
- When `@ManagedExecutorConfig` is used on a `ManagedExecutor` injection point with one or more CDI qualifiers (such as `@NamedInstance`), the container will produce an aptly configured `ManagedExecutor` for all injection points with the corresponding qualifiers.

To me this seems straightforward because it can be fully described in terms of injection points, producers, and qualifiers -- concepts that CDI users will already be familiar with.  No mention of unique names and how they get synthesized.

---

For option 54, this does not seem completely true:
> @NamedInstance is a standard CDI Qualifier...
 
With this option, `@NamedInstance` has special meaning and can only be processed by the container -- it cannot be used by app-defined producers, so it's not a standard CDI Qualifier. 

The config annotation is clearly for container use only, but the `@NamedInstance` annotation is a CDI qualifier (provided for convenience by the spec), so I think it would be best if the spec did not impose extra restrictions on it.

Regarding this statement:

>> The container creates, per unique name, a new ManagedExecutor instance, if the application does not produce one.

> Not sure we need the bit about not producing one if user does.
We simply provide beans (metadata) for all unique names. If user provides their own producer as an enabled alternative, their bean definition (defined as a producer) will be used instead. That's just how CDI works. I think we could just leave it out.

I think it's important that the container does not interfere with scenarios where neither `@NamedInstance` nor `@ManagedExecutorConfig` are being used.
For example, I would hope the container doesn't interfere with this scenario...
```java
public class MyBean {
  @Produces
  @MyQualifier
  public ManagedExecutor produce() { /* ... */ }

  @Inject
  @MyQualifier
  ManagedExecutor injected; 
  // 'com.foo.MyBean.injected' name is synthesized here by the container
  // Does the container try to produce this and does it interfere with the app-defined producer?
}
```

As long as the container doesn't interfere with the above scenario, I would be OK with Option 54.

**Comment by manovotn** [comment]
> With this option, @NamedInstance has special meaning and can only be processed by the container -- it cannot be used by app-defined producers, so it's not a standard CDI Qualifier.

It can be used as qualifier in your own producers.

```
@Inject
@MyQualifier
@NamedInstance("foo")
ManagedExecutor me;
```

Even in this case the container doesn't need to interfere and you can do that. Or you can override container provided bean as follows:

```
@NamedInstance("foo")
@Produces
@Alternative
@Priority(x)
public ManagedExecutor createME() {...}
```

> As long as the container doesn't interfere with the above scenario, I would be OK with Option 54.

Yea it won't interfere. It should only care about cases where there is config, NamedInstance, both or none of them + no other qualifier.

**Comment by aguibert** [comment]
Sounds good to me, lets go with option 54

**Comment by njr-11** [comment]
This latter interpretation of option 54 unfortunately compromises away everything I've been asked to represent by the subject matter experts within my own company with regard to CDI-based configuration for this spec.  There are two opposing viewpoints here, both from experts who know far more about CDI than myself, and I've been trying to bring both toward some sort of compromise. 

The first viewpoint, which is well-represented in the various discussions, favors an approach where the container creates instances of `ManagedExecutor` based on injection points that are annotated with configuration detail (`@ManagedExecutorConfig`).

The second viewpoint, from my own company's subject matter experts, which I've been struggling to adequately represent, is that CDI injection points are an improper place to specify configuration detail, and that we should instead solve the problem of custom configuration (as well as sharing) with simple copy/pasteable examples of writing a CDI producer that leverages a spec defined qualifier (`@NamedInstance`).

Specifically, this means the following patterns must be possible:
```
@Produces @NamedInstance("exec1")
ManagedExecutor createExec1() { return ManagedExecutor.builder().maxAsync(5).build(); }

@Produces @NamedInstance("exec2")
ManagedExecutor createExec2() { return ManagedExecutor.builder().propagated(ThreadContext.SECURITY).build(); }

@Inject @NamedInstance("exec2") ManagedExecutor executor;
```

My efforts to merge these two approaches together into a compromise solution at first seemed successful. However, our attempt to write it up in the spec has revealed that we were never entirely on the same page about exactly what the compromise solution is.  Option 54 as I most recently wrote it up (including the language ["if the application does not produce one"](https://github.com/eclipse/microprofile-concurrency/issues/43#issuecomment-445280712)) compromises as much away as I possibly could without completely abandoning every one of the goals that I was asked to represent by my company's own experts in the area.  With further concessions beyond this point, the spec becomes entirely aligned with one side and in opposition to the other.  If that happens because I'm completely outvoted, we need to seriously consider whether `@NamedInstance` should even remain in the spec, because the purpose for which it was wanted in the first place is being eliminated.

**Comment by njr-11** [comment]
On this week's MP Concurrency call, we came up with the resolution of using pull #54 but updating it with the requirement from pull #53 that `@NamedInstance` is a standard CDI Qualifier that can be used by application-defined producers without needing to specify Alternative.
