### ISSUE TITLE
Refactor `ConcurrencyManagerBuilder`?

### ISSUE THREAD

**Issue by FroMage** [eclipse/microprofile-concurrency#49]
The other builders got put into inner interfaces, should I refactor this one as well?

**Comment by njr-11** [comment]
Given that ConcurrencyManager/ConcurrencyManagerBuilder are SPI and will be far less frequently used (in integration code rather than applications), I don't think this is necessary, although I'm fine with whichever way you prefer it.

To be honest, I didn't see there being all that much benefit to switching the other builders to inner classes either, but was happy to go along with what the community wanted.

**Comment by FroMage** [comment]
Well, I don't see value either, but for consistency I think it'd be better. I'll do a PR.
