### ISSUE TITLE
ThreadContext#currentContextExecutorRunsWithContext TCK test question

### ISSUE THREAD

**Issue by manovotn** [eclipse/microprofile-concurrency#74]
Not sure if this is intentional, but [`ThreadContextTest`](https://github.com/eclipse/microprofile-concurrency/blob/master/tck/src/main/java/org/eclipse/microprofile/concurrency/tck/ThreadContextTest.java#L680) at one point assumes that configuring TC builder with `propagated` only and then calling `currentContextExecutor()` will result in executor that clears all contexts that weren't specifically mentioned.

[This assertion](https://github.com/eclipse/microprofile-concurrency/blob/master/tck/src/main/java/org/eclipse/microprofile/concurrency/tck/ThreadContextTest.java#L706-L707) even states (as fail msg) that "Context type that is configured to be cleared was not cleared." 

This IMO doesn't need to be the case because of our default values for undefined properties of TC. In case of this test, you will end up with:
_propagated - [Buffer]
cleared - [Transaction]
unchanged - []_

Is the test missing builder configuration for `cleared`, or am I missing something instead? :)
CCing @nmittles as he is the author.

**Comment by njr-11** [comment]
I think I previously reviewed the pull that added this test, and I believe the test is valid as the [ThreadContext.Builder JavaDoc](https://github.com/eclipse/microprofile-concurrency/blob/master/api/src/main/java/org/eclipse/microprofile/concurrent/ThreadContext.java) is currently written.  On lines 152-154 documenting the propagated() method, it states,
`Thread context types which are not otherwise included in this set or in the {@link #unchanged} set are cleared from the thread of execution for the duration of the action or task.`  The ThreadContextConfig.propagated method has a corresponding identical statement, and both ManagedExecutor.Builder.propagated and ManagedExecutorConfig.propagated have corresponding statements as well.

These statements (which are remnants of the design before we had the ALL_REMAINING constant) address the question of what to do with context types that are not specified in any list (cleared/propagated/unchanged).  For the sake of consistency across implementations, I believe it's a good idea for the spec to standardize on a behavior here, whether that be what is currently stated or otherwise if we think of something better.

The main alternative that I can think of is declaring it a configuration error (IllegalStateException upon build() and DefinitionException upon injection) when the user does not configure what to do with an available context type.  The main advantage here would be forcing the application to be explicit about what happens to every context type, such that the reader of the code will know exactly what happens to those other context types without consulting the JavaDoc.

The main advantage to the spec/JavaDoc as written is that it optimizes configuration toward the pattern where the user only cares to think about specifying what they want propagated, and they aim to write code as concisely as possible.  The spec then enforces a standard approach of clearing out the context types that they didn't care to specify, because that the only safe approach to infer.

**Comment by manovotn** [comment]
@njr-11 I see, I simply missed that bit in the docs (was looking at TC itself, not the builders).
Thanks for pointing it out! It does make sense to define the behaviour in the spec for sure.
Handling it the way we have now is probably better as adding a context in future won't break existing setup in builders (which it would should we throw ISE).

I'll leave it up to you whether you want to merge the PR or not.
I'd nice to have the test clear but in the same time we should test the behaviour you described.

**Comment by njr-11** [comment]
@manovotn that is an excellent point about maintaining compatibility when additional context types are added in the future.  Regarding the PR, I'll go ahead and merge it so the test is more clear.  We can then add a separate TCK test that has the explicit purpose of covering this statement in the JavaDoc.

**Comment by FroMage** [comment]
So, then `cleared` defaults to `ALL_REMAINING` if `propagated` is not the default. I guess that's useful, but it's not at all clear from the javadoc of `cleared` which only mentions defaulting to `TRANSACTION`. We should update that javadoc to mention that.
