### ISSUE TITLE
State of Futures after shutting down executors

### ISSUE THREAD

**Issue by manovotn** [eclipse/microprofile-concurrency#78]
I was looking at current TCK tests and the docs we have around it.

[TCK seems to assume](https://github.com/eclipse/microprofile-concurrency/blob/master/tck/src/main/java/org/eclipse/microprofile/concurrency/tck/ManagedExecutorTest.java#L963-L969) that all the references to `CompletableFuture` are in cancelled state after you shut down the executor. This however isn't what the spec says and IMO isn't even desirable behaviour because it goes against what other executors normally do. Standard behaviour is not to touch those and you can query your futures with timeouts or just check if `!f.isDone() && !f.isCancelled() && exec.isTerminated()` or maybe compare the runnables you passed there to those you got back from `shutdownNow()`.

As for ours docs, the only bit I found is a javadoc on MEBuilder (and similar piece on TCBuilder) which states:

> All created instances of ManagedExecutor are destroyed when the application is stopped. The container automatically shuts down these managed executors and **cancels their remaining actions/tasks**.

This bit speaks about what happens _when application is stopped_ at which point it doesn't really matter what state are the futures in as long as the executor shutdown is graceful which it is.

**Comment by njr-11** [comment]
As discussed on the MP Concurrency call today, we agreed to change the TCK test.  Our implementation (Open Liberty) also experienced the hang in this test, and although I've since updated our implementation to get the status of CompletableFutures updated to canceled instead of remaining not-done after shutdownNow, this part of the test does seem to be overreaching what the spec actually states and so the test should not be enforcing this behavior.
