### ISSUE TITLE
Add `ThreadContext.withCurrentContext(CompletionStage)`

### ISSUE THREAD

**Issue by FroMage** [eclipse/microprofile-concurrency#9]
We need to be able to wrap more types for context, such as `CompletionStage` and `CompletableFuture`.

See: https://github.com/reactiverse/reactive-contexts/blob/master/core/src/main/java/io/reactiverse/reactivecontexts/core/Context.java#L308

**Comment by njr-11** [comment]
For this, we need some clarification on what it means to wrap an existing CompletionStage or CompletableFuture with context.

Note that ManagedExecutor methods supplyAsync, runAsync, completedFuture, completedStage, failedFuture, failedStage allow for creating a new instance of CompletableFuture or CompletionStage that is contextualized and for which context propagation applies to all dependent stages.  This is possible because new CompletableFuture/CompletionStage instances  are are created and so are able to implement the hook methods newIncompleteFuture and defaultExecutor.

However, given a pre-existing, noncontextual CompletableFuture/CompletionStage, there is no way to force it to run with context that it doesn't already have, and there is no way to force it to start creating dependent stages that are contextual.

The closest I can see getting to what I think this might be asking for is to potentially tie the life cycle of a wrapper CompletableFuture to a non-contextualized CompletableFuture.  CompletableFutures from a ManagedExecutor can already do this, although it is a bit awkward,
```
completableFutureForNonContextualActionWithContextualDependentActions =
  managedExecutor.completedFuture(unused)
                 .thenCompose((unused) -> { return nonContextualizedCompletableFuture; });
```
but even so, the action performed by the `nonContextualizedCompletableFuture` remains non-contextual.

The ThreadContext API does already provide methods for contextualizing all of the actions that you can supply to a CompletableFuture/CompletionStage, such that individual actions can easily be made to run with context.

**Comment by FroMage** [comment]
I believe the same wrapper required to pin the default executor can work to apply context to each stage:

https://github.com/smallrye/smallrye-concurrency/blob/master/core/src/main/java/io/smallrye/concurrency/impl/CompletableFutureWrapper.java
https://github.com/smallrye/smallrye-concurrency/blob/master/core/src/main/java/io/smallrye/concurrency/impl/CompletionStageWrapper.java

**Comment by FroMage** [comment]
But you're right, this is only valid for stages that are registered after contextualising. However at least it does not require manually contextualising each further stage with `ThreadContext`

**Comment by njr-11** [comment]
Thanks for providing the examples. This gives me a better idea of what you are trying to accomplish with dependent stages, and I think you may be slightly misinterpreting the current language of the spec regarding which context to capture/apply to dependent stage actions for a CompletionStage or CompletableFuture that is created by a ManagedExecutor. If I understand correctly, it looks like your example aims to capture thread context when the completion stage is initially created and then apply that same context to all dependent stages that are created from it. However, the ManagedExecutor JavaDoc specifies a subtly different requirement:

_"When dependent stages are created from the completion stage, and likewise from any dependent stages created from those, and so on, thread context is captured from the thread that creates the dependent stage. This guarantees that the action performed by each stage always runs under the thread context of the code that creates the stage."_

The above means that thread context is captured each time a dependent stage is created, and is subsequently applied to the action associated with that stage.

We will need to determine if the ManagedExecutor JavaDoc is not clear enough here or if you found conflicting text elsewhere in the spec (The latter is definitely a possibility - if so, please point it out).
The reasons behind this requirement in the spec are twofold.
First, it provides consistency and predictability (the approach you followed accomplishes this as well).
Second, it limits code that tacks on a dependent stage to only being able to donate its own context to that stage. Otherwise, we open a security hole where anyone who submits a dependent stage can get it to run under context that was intended for an earlier stage in the chain. Then it becomes unsafe to return CompletionStages from various API that builds upon this spec, with the driving force behind the creation of this spec being for MicroProfile FaultTolerance and JAX-RS to do exactly that.

If you switch the example over to align with the requirement for dependent stage context, then I think what is being asked for in this issue will no longer be needed. It will no longer be necessary to pass the previously captured context along, and just capture context anew with each wrapped method that adds a dependent action.
If you agree, we can use this issue to fix/improve the JavaDoc or other spec language so that it's clear to all implementors.

**Comment by FroMage** [comment]
No, what happened was that I had these wrappers in Reactive Contexts, and did not re-create them from scratch for MP-Concurrency. I guess I do agree with the idea of capturing context on stage creation, though in practice it never happened in our code bases that the context differed between initial creation and later stages, so we never noticed any issue. In fact the most important thing is to keep the same request context from the start to the end of the request, so in both cases the contexts will be the same one.

Nevertheless, we added `Context.wrap(CompletionStage)` (which would be `ThreadContext.withCurrentContext(CompletionStage)` so that our users would be able to do this:

```java
Context.wrap(someCompletionStageApi())
 .thenApply(...)
 .exceptionally(...)
```

Without having to call `Context.wrap()` (here `ThreadContext.withCurrentContext()`) for each stage, because in practice there are often many. So it would still be useful to have this wrapper, even if the semantics is altered to what you explained.

**Comment by njr-11** [comment]
Thanks for explaining further.  I agree that it could still be useful to have, although we will need a name other than `withCurrentContext` to better reflect the semantics and to help avoid confusion over what it does.  I went looking through the CompletableFuture API for related methods to help on naming, and I found this method,
https://docs.oracle.com/javase/10/docs/api/java/util/concurrent/CompletableFuture.html#copy()
If I understand correctly, our new method would be creating a copy of the existing CompletableFuture/CompletionStage, where dependent stages made from the copied stage capture & propagate context to their respective dependent actions.  It should be noted that such a method could equally well apply to ManagedExecutor as to ThreadContext.  Would it make more sense to put the new method onto ManagedExecutor so that it can also have async dependent stages default to running on the ManagedExecutor?

**Comment by FroMage** [comment]
Well, we can argue that `withCurrentContext` is still valid because it will apply the context that is current at the time of each stage creation. I'd be OK with `withContextPropagation` or `withContextCapture` too. I don't feel that `copy` indicates that the result will be any different in how it deals with context.

As for putting it on `ManagedExecutor` I'm not too keen because in most reactive libs the events are triggered by special schedulers/event-loops that the user doesn't change, so in most code I've written and seen the `async` variant methods are just never used, and even in some cases actively prohibited. But it could still use the `ManagedExecutor` underneath (in my case I just wouldn't use it, so it would not matter).

**Comment by njr-11** [comment]
`withContextCapture` is a good name for it because it doesn't imply anything about when the context is captured, which we can then elaborate on in the JavaDoc.  It also doesn't imply that it impacts anything that was already requested (the action of the supplied stage, or dependent stages that have already been requested).  Context capture implies something that will naturally happen upon dependent actions being created from the resulting stage.  I'm fine with adding this to `ThreadContext` rather than `ManagedExecutor` given that we still have the opportunity to make the default executor for it be a thread pool that is managed the container.  This can be clarified in the JavaDoc.
